### ISSUE TITLE
bug: Command Failed - npm install 

### ISSUE THREAD

**Issue by jochasinga** [FIL-Builders/fil-frame#55]
Node.js v20.7.0 (lts/iron)
npm 10.9.0
Mac OS 13.6.7

### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/FIL-Builders/fil-frame/issues)

### Current Behavior

1. Run `npx create-filecoin-app`
2. Choose directory name / directory created
3. Choose `Default` storage
4. Choose `npm` as the package manager

The terminal idles for a few minutes, then exit with an error.

Additionally, the directory was created with a `yarn.lock` in it.

```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: @fil-frame/hardhat@0.0.1
npm error Found: hardhat-deploy@0.11.45
npm error node_modules/hardhat-deploy
npm error   dev hardhat-deploy@"^0.11.45" from @fil-frame/hardhat@0.0.1
npm error   packages/hardhat
npm error     @fil-frame/hardhat@0.0.1
npm error     node_modules/@fil-frame/hardhat
npm error       workspace packages/hardhat from the root project
npm error
npm error Could not resolve dependency:
npm error peer hardhat-deploy@"^0.12.0" from hardhat-deploy-ethers@0.4.2
npm error node_modules/hardhat-deploy-ethers
npm error   dev hardhat-deploy-ethers@"^0.4.1" from @fil-frame/hardhat@0.0.1
npm error   packages/hardhat
npm error     @fil-frame/hardhat@0.0.1
npm error     node_modules/@fil-frame/hardhat
npm error       workspace packages/hardhat from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/pancy/.npm/_logs/2024-11-09T07_23_03_060Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/pancy/.npm/_logs/2024-11-09T07_23_03_060Z-debug-0.log
node:internal/errors:865
  const err = new Error(message);
              ^

Error: Command failed: npm install
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at runPackageInstall (file:///Users/pancy/.npm/_npx/cf5e186f4e87c90d/node_modules/create-filecoin-app/dist/index.js:39:5)
    at createFilecoinApp (file:///Users/pancy/.npm/_npx/cf5e186f4e87c90d/node_modules/create-filecoin-app/dist/index.js:48:5)
    at interactiveMode (file:///Users/pancy/.npm/_npx/cf5e186f4e87c90d/node_modules/create-filecoin-app/dist/index.js:81:11)
    at async Command.<anonymous> (file:///Users/pancy/.npm/_npx/cf5e186f4e87c90d/node_modules/create-filecoin-app/dist/index.js:91:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 38865,
  stdout: null,
  stderr: null
}

Node.js v20.7.0
```

### Expected Behavior

- The CLI continues to install dependencies with `npm`.
- If it fails at all, the directory shouldn't be created.

### Steps To Reproduce

See above.

### Anything else?

Find attached log file

[2024-11-09T07_23_03_060Z-eresolve-report.txt](https://github.com/user-attachments/files/17686433/2024-11-09T07_23_03_060Z-eresolve-report.txt)

**Comment by jochasinga** [comment]
Running `npm i` inside the created directory reproduced the exact same error. The error code is `ERESOLVE` on hardhat.

**Comment by xBalbinus** [comment]
Please use yarn. I think this is an issue with using an inappropriate package manager.
